# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be

#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

def generate_fib
  fib = [1, 2]

  while (fib[-1] + fib[-2]) < 4000000
    fib << fib[-1] + fib[-2]
  end

  fib
end

def sum_of_even_fibs
  generate_fib.reduce(0) { |sum, n| n % 2 == 0 ? sum + n : sum }
end

puts sum_of_even_fibs
